### ISSUE TITLE
Support Cargo.toml features to allow build on Windows

### ISSUE THREAD

**Issue by davidpodhola** [kaj/nickel-jwt-session#11]
First of all, thank you very much for the project, it fits very well into what I am trying to achieve.

However I am on Windows and OpenSSL now does not work very well here. Actually it prevents `nickel-jwt-session` to be used at all.

I was [able to compile `nickel-jwt-session` on Windows](https://github.com/hsharpsoftware/rust-realworld-example-app/issues/1), but I do not think my approach including the source code is good.

> Speculation: I think it would be enough to support features and pass them to the other crates used.

Please let me know if you like this, thanks!

**Comment by kaj** [comment]
I don't know that much about cargo features yet, can I make a feature of this crate that disables default features of dependency crates?

I'll do some experimenting and report back soonish.

**Comment by kaj** [comment]
Actually, it seems that the effect of `default-features = false` does not forbid default features, it just does not require them.  So if nickel-jwt-session requires hyper with default-features = false, and an application crate requires both nickel-jwt-session and hyper (with default features), the application will get hyper with default features and apparently no conflict.

So, I will just make a release of nickel-jwt-session without default features of hyper and cookie and hope that it solves your problem without breaking stuff for me or anyone else.  :-)

**Comment by davidpodhola** [comment]
Great, thanks, that should work exactly how I need it :-)

**Comment by kaj** [comment]
Huh?  Github closed the issue when I mentioned it in a commit?  Ah well.

Release 0.6.0, which should fix this problem, is on crates.io now.

**Comment by davidpodhola** [comment]
Awesome, thanks a lot, working for me and I can now delete my ugly `lib` folder and use the one from crates.io!

Yes, those [reserved words in commit](https://help.github.com/articles/closing-issues-via-commit-messages/) always confuse me too.
