### ISSUE TITLE
Authorization: Bearer

### ISSUE THREAD

**Issue by stephanbuys** [kaj/nickel-jwt-session#2]
Hi there, I'm just getting started with Nickel and I'm super interested in your plugin, can even try and assist with improvements/etc. Is it possible through the current API to get the jwt as a Authorization: Bearer <xxx> header?

**Comment by kaj** [comment]
Not through the current API, it only supports a cookie (even the name of the cookie is hardcoded).  It should be relatively simple to add, though I'm not sure if the Authorization header should always be accepted or if there should be some way to enable / disable it.

**Comment by kaj** [comment]
@stephanbuys, do you have any comments on the solution from @carols10cents?

**Comment by stephanbuys** [comment]
Hi @kaj this is exactly what I was looking for, I contracted @carols10cents from Integer32 to add the functionality 😄

**Comment by kaj** [comment]
The PR is merged and release 0.3.0 with the new feature is pushed to crates.io.
