### ISSUE TITLE
Nickel/plugin question

### ISSUE THREAD

**Issue by stephanbuys** [kaj/nickel-jwt-session#4]
Is there a way to make JWT authentication a default behaviour for a set of routes? This might be more of a Nickel.rs question than a plugin question, not certain.

**Comment by carols10cents** [comment]
I _think_ I've got the start to something for this, but I don't have all the pieces hooked together right: https://github.com/integer32llc/nickel-jwt-session/commit/ca88b0a87cf8740ca0296d613dd3aa7257498d77

I'm going to try again with fresh eyes tomorrow.

**Comment by kaj** [comment]
I assume you mean requiring an authenticated user for certain routes?  If so, I agree with @carols10cents that this is probably more of a documentation / example or even a nickel issue.  A sub-router requiring an authenticated user sounds like the right way to do it.  Maybe we should even provide such a sub-router in the crate, if nickel doesn't make it so easy its not needed.

**Comment by carols10cents** [comment]
@stephanbuys liked the sub-router I added to the example in https://github.com/kaj/nickel-jwt-session/pull/7/commits/5327fd3afc3a4e266da58b8f8871a1ddf62443cf. 

I don't think we could include much in the crate, maybe [the struct and the initializer](https://github.com/kaj/nickel-jwt-session/pull/7/commits/5327fd3afc3a4e266da58b8f8871a1ddf62443cf#diff-61ce5021c678ba54cdb41b7178c8701eR77), but that's only like 8 lines of boilerplate. The [implementation of `invoke` for that middleware is likely to be different in every application](https://github.com/kaj/nickel-jwt-session/pull/7/commits/5327fd3afc3a4e266da58b8f8871a1ddf62443cf#diff-61ce5021c678ba54cdb41b7178c8701eR92).

**Comment by kaj** [comment]
Hm, apparently merging PR #7 which referenced this issue also closed this issue automatically.  Well, I guess it really is resolved by the new example.  Otherwise please reopen, @stephanbuys .

**Comment by stephanbuys** [comment]
All good thanks!
