### ISSUE TITLE
announcement on reddit

### ISSUE THREAD

**Issue by stephanbuys** [kaj/nickel-jwt-session#5]
Hi @kaj, would you mind if I write a short note about @carols10cents 's work? I want to give their company a bit of publicity, and see if I can drum up some testers/contributors.

**Comment by kaj** [comment]
Fine by me.  I'm not on reddit myself, but more users / testers / contributors are always welcome!  :-)

**Comment by stephanbuys** [comment]
Announced on https://www.reddit.com/r/rust/comments/4xcacg/announcing_a_much_improved_nickel_jwt_middleware/
